# Generated by Django 3.2.8 on 2021-11-19 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='Contact1',
        ),
    ]
